version: '3'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  bot:
    command: sh -c "./scripts/run.sh"
    build:
      context: bot/
    volumes:
      - ./bot/:/code/
    depends_on:
      - database
    env_file:
      - envs/bot.env
      - envs/database.env
