"""Add tic tac toe structure

Revision ID: 18bdc84d9539
Revises: 
Create Date: 2020-07-26 22:22:09.095491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bdc84d9539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TicTacToeGame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('status', sa.Enum('initial', 'in_progress', 'finished', name='enumstatus'), nullable=False),
    sa.Column('current_step_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_step_user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TicTacToePlayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sign', sa.Enum('cross', 'circle', name='enumsign'), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['TicTacToeGame.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TicTacToeStep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['TicTacToePlayer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TicTacToeStep')
    op.drop_table('TicTacToePlayer')
    op.drop_table('TicTacToeGame')
    op.drop_table('User')
    # ### end Alembic commands ###
