"""Set current_step_user_id nullable

Revision ID: 9796c70df9ac
Revises: 18bdc84d9539
Create Date: 2020-07-30 22:42:35.811782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9796c70df9ac'
down_revision = '18bdc84d9539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TicTacToeGame', 'current_step_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TicTacToeGame', 'current_step_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
