"""Add tic tac toe structure

Revision ID: cdf449c6aba6
Revises: 
Create Date: 2020-07-26 15:34:50.307411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf449c6aba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tictactoegame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('initial', 'in_progress', 'finished', name='enumstatus'), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_step'], ['Tictactoeplayer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tictactoeplayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('sign', sa.Enum('cross', 'circle', name='enumsign'), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Tictactoegame.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tictactoestep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['Tictactoeplayer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tictactoestep')
    op.drop_table('User')
    op.drop_table('Tictactoeplayer')
    op.drop_table('Tictactoegame')
    # ### end Alembic commands ###
